# Generated by Django 3.1 on 2020-08-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items_debted_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Price', models.IntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.debts_out')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='items_debted_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Price', models.IntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.debts_in')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
