# Generated by Django 3.1 on 2020-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_auto_20200823_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debts_in',
            options={'verbose_name_plural': 'debts_in'},
        ),
        migrations.AlterModelOptions(
            name='debts_out',
            options={'verbose_name_plural': 'debts_out'},
        ),
        migrations.AddField(
            model_name='debts_in',
            name='clearance',
            field=models.CharField(choices=[('Y', 'Cleared'), ('N', 'Not cleared')], default=' ', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debts_out',
            name='clearance',
            field=models.CharField(choices=[('Y', 'Cleared'), ('N', 'Not cleared')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items_debted_in',
            name='situation',
            field=models.CharField(choices=[('p', 'Paid'), ('N', 'Not paid')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items_debted_out',
            name='situation',
            field=models.CharField(choices=[('p', 'Paid'), ('N', 'Not paid')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
