# Generated by Django 3.1 on 2020-08-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_auto_20200829_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts_in',
            name='Overall_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debts_out',
            name='Overall_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items_debted_in',
            name='Overall_item_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items_debted_out',
            name='Overall_item_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
