# Generated by Django 3.1 on 2020-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_auto_20200829_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_debted_in',
            name='situation_2',
            field=models.BooleanField(default=True),
        ),
    ]
