# Generated by Django 3.1 on 2020-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0007_items_debted_in_situation_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_debted_in',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='items_debted_out',
            name='situation',
        ),
        migrations.AddField(
            model_name='items_debted_out',
            name='situation_2',
            field=models.BooleanField(default=True),
        ),
    ]
