# Generated by Django 3.1 on 2020-07-19 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0010_auto_20200719_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts_out',
            name='Balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debts_out',
            name='Paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='situation_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=10)),
                ('Date_paid', models.CharField(max_length=20)),
                ('Amount_paid', models.PositiveIntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.debts_out')),
            ],
        ),
    ]
