# Generated by Django 3.1 on 2020-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0011_auto_20200719_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts_in',
            name='Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debts_in',
            name='Overall_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debts_in',
            name='Paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debts_out',
            name='Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debts_out',
            name='Paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items_debted_in',
            name='Overall_item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items_debted_in',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items_debted_out',
            name='Overall_item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items_debted_out',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='situation_in',
            name='Amount_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='situation_out',
            name='Amount_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='situation_out',
            name='Date_paid',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
