# Generated by Django 3.1 on 2020-12-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0013_auto_20201004_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='undefined_credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Date', models.DateTimeField()),
                ('Amount', models.IntegerField()),
                ('Overall_price', models.PositiveIntegerField(blank=True, null=True)),
                ('Paid', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('clearance', models.CharField(choices=[('Y', 'Cleared'), ('N', 'Not cleared')], max_length=1)),
                ('situation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='undefined_debts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Date', models.DateTimeField()),
                ('Amount', models.IntegerField()),
                ('Overall_price', models.PositiveIntegerField(blank=True, null=True)),
                ('Paid', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('clearance', models.CharField(choices=[('Y', 'Cleared'), ('N', 'Not cleared')], max_length=1)),
                ('situation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='undefined_debts_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_paid', models.DateTimeField(auto_created=True)),
                ('Day', models.CharField(max_length=10)),
                ('Amount_paid', models.IntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.undefined_debts')),
            ],
        ),
        migrations.CreateModel(
            name='undefined_credit_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_paid', models.DateTimeField(auto_created=True)),
                ('Day', models.CharField(max_length=10)),
                ('Amount_paid', models.IntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.undefined_credit')),
            ],
        ),
    ]
