# Generated by Django 3.1 on 2020-08-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'stock'},
        ),
    ]
