# Generated by Django 3.1 on 2020-08-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200829_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='overall_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
