# Generated by Django 3.1 on 2020-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='product-thumbnails'),
        ),
    ]
