# Generated by Django 3.1 on 2020-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(null=True, upload_to='product-images'),
        ),
        migrations.AddField(
            model_name='stock',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='product-thumbs'),
        ),
        migrations.DeleteModel(
            name='product_img',
        ),
    ]
