# Generated by Django 3.1 on 2020-10-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_stock_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Category',
            field=models.CharField(blank=True, choices=[('P', 'Plumbing'), ('T', 'Tiles'), ('B', 'Bathroom accessories')], max_length=35, null=True),
        ),
    ]
