# Generated by Django 3.1 on 2020-11-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20201031_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Category',
            field=models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Tiles', 'Tiles'), ('Bathroom accessories', 'Bathroom accessories')], max_length=35, null=True),
        ),
    ]
