# Generated by Django 3.1 on 2020-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20201101_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Name',
            field=models.CharField(max_length=100),
        ),
    ]
