# Generated by Django 3.1 on 2020-09-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0007_auto_20200902_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Selling_price', models.PositiveIntegerField()),
                ('Total_price', models.PositiveIntegerField()),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_sales.daily_sales')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
