# Generated by Django 3.1 on 2020-09-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_sales',
            name='Date',
        ),
    ]
