# Generated by Django 3.1 on 2020-09-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0002_remove_daily_sales_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily_sales',
            options={'verbose_name_plural': 'daily sales'},
        ),
    ]
