# Generated by Django 3.1 on 2020-09-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0004_auto_20200912_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_entry',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
