# Generated by Django 3.1 on 2020-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0008_auto_20200716_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='Total_sales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
