# Generated by Django 3.1 on 2020-07-18 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0009_daily_sales_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='Date_sold',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
