# Generated by Django 3.1 on 2020-07-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0010_daily_sales_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_sales',
            name='Date_sold',
            field=models.DateTimeField(),
        ),
    ]
