# Generated by Django 3.1 on 2020-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0011_auto_20200719_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_sales',
            name='Total_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_entry',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_entry',
            name='Selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_entry',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
