# Generated by Django 3.1 on 2020-10-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20200902_1049'),
        ('daily_sales', '0012_auto_20200719_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_sold', models.DateTimeField(auto_created=True)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=13)),
                ('Overall_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Selling_price', models.IntegerField()),
                ('Overall_item_price', models.IntegerField(blank=True, null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_sales.receipts')),
            ],
        ),
    ]
