# Generated by Django 3.1 on 2020-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0013_receipt_items_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_items',
            name='Overall_item_price',
            field=models.IntegerField(),
        ),
    ]
