# Generated by Django 3.1 on 2020-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0014_auto_20201003_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_items',
            name='Overall_item_price',
            field=models.IntegerField(blank=True,  null=True),
        ),
    ]
