# Generated by Django 3.1 on 2020-10-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0017_auto_20201003_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'verbose_name_plural': 'Receipts'},
        ),
    ]
