# Generated by Django 3.1 on 2020-11-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20201101_1030'),
        ('daily_sales', '0018_auto_20201004_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_entry',
            name='Day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daily_sales.daily_sales'),
        ),
        migrations.AlterField(
            model_name='product_entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Day_items', to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='receipt_items',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name_items', to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='receipt_items',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daily_sales.receipts'),
        ),
    ]
