# Generated by Django 3.1 on 2020-11-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0020_auto_20201119_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_items',
            name='Overall_item_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_items',
            name='Selling_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
