# Generated by Django 3.1 on 2020-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0022_auto_20201119_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_sales',
            name='Date_sold',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
