# Generated by Django 3.1 on 2020-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0023_auto_20201123_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_sales',
            name='Date_sold',
            field=models.DateTimeField(),
        ),
    ]
