# Generated by Django 3.1 on 2020-07-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0024_auto_20201123_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_entry',
            name='Profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
