# Generated by Django 3.1 on 2020-07-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sales', '0025_product_entry_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
