# Generated by Django 3.1 on 2020-11-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plumbing_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=18)),
                ('Contact', models.CharField(max_length=13)),
                ('EMail', models.EmailField(blank=True, max_length=40)),
                ('Password', models.CharField(default=0, max_length=10)),
                ('Status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Plumbing Services',
            },
        ),
        migrations.CreateModel(
            name='Tiling_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=18)),
                ('Contact', models.CharField(max_length=12)),
                ('Email', models.EmailField(blank=True, max_length=40)),
                ('Password', models.CharField(default=0, max_length=10)),
                ('Status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tiling services',
            },
        ),
        migrations.CreateModel(
            name='images_tiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site/tiling')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.tiling_services')),
            ],
        ),
        migrations.CreateModel(
            name='images_plumbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site/plumbing')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.plumbing_services')),
            ],
        ),
    ]
