# Generated by Django 3.1 on 2020-11-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plumbing_services',
            name='profile_pic',
            field=models.ImageField(default='ceramic-tile-22515358.jpg', upload_to='site/plumbing'),
        ),
        migrations.AddField(
            model_name='tiling_services',
            name='profile_pic',
            field=models.ImageField(default='ceramic-tile-22515358.jpg', upload_to='site/tiling'),
        ),
    ]
