# Generated by Django 3.1 on 2020-11-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20201104_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbing_services',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='site/plumbing/'),
        ),
        migrations.AlterField(
            model_name='tiling_services',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='site/tiling/'),
        ),
    ]
