# Generated by Django 3.1 on 2020-11-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_auto_20201104_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiling_services',
            name='Contact',
            field=models.CharField(max_length=13),
        ),
    ]
